// Display translations only. Calculation inputs and engine outputs remain unchanged.
export const korean: Record<string,string> = {
Tree:"목 · T",Fire:"화 · F",Earth:"토 · E",Metal:"금 · M",Water:"수 · W",
Jupiter:"목성",Mars:"화성",Venus:"금성",Mercury:"수성",Sunlit:"양 · 陽",Moonlit:"음 · 陰",
"Ancient Soul":"오래된 영혼 유형","Mature Soul":"성숙한 영혼 유형","Balanced Soul":"균형 잡힌 영혼 유형",
"Blue Jupiter Aura":"푸른 목성의 기운","Red Mars Aura":"붉은 화성의 기운","Golden Earth Aura":"황금빛 지구의 기운","Silver Venus Aura":"은빛 금성의 기운","Dark Mercury Aura":"깊은 수성의 기운",
"Forest Explorer":"숲의 탐험가","Flame Warrior":"불꽃의 전사","Mountain Strategist":"산의 전략가","Silver General":"은빛 장군","Ocean Sage":"바다의 현자",
"Growth, vision, movement":"성장, 비전, 움직임","Overextension and impatience":"지나친 확장과 조급함","Metal discipline":"금의 기운으로 절제하기",
"Charisma, passion, visibility":"카리스마, 열정, 존재감","Burnout and impulsive action":"소진과 충동적인 행동","Water strategy":"수의 기운으로 전략 세우기",
"Stability, endurance, responsibility":"안정감, 인내, 책임감","Stagnation and overthinking":"정체와 지나친 고민","Tree growth":"목의 기운으로 성장하기",
"Precision, discipline, judgment":"정확성, 절제, 판단력","Rigidity and isolation":"경직과 고립","Fire expression":"화의 기운으로 표현하기",
"Wisdom, adaptability, hidden strategy":"지혜, 적응력, 내면의 전략","Hesitation and emotional distance":"망설임과 감정적 거리","Earth grounding":"토의 기운으로 중심 잡기",
Builder:"성장형",Promoter:"표현형",Accumulator:"축적형",Executor:"실행형",Strategist:"전략형",Explorer:"탐험형",Magnet:"매력형",Guardian:"보호형",Commander:"주도형",Observer:"관찰형",
"You create value through growth, ideas, education, and long-term development.":"성장, 아이디어, 교육과 장기적인 발전을 통해 가치를 만듭니다.",
"You create value through visibility, influence, branding, and fast movement.":"존재감, 영향력, 브랜딩과 빠른 행동을 통해 가치를 만듭니다.",
"You create value slowly through stability, assets, systems, and responsibility.":"안정, 자산, 체계와 책임감을 바탕으로 가치를 차근차근 쌓습니다.",
"You create value through precision, discipline, quality, and decisive action.":"정확성, 절제, 품질과 결단력 있는 행동으로 가치를 만듭니다.",
"You create value through information, timing, adaptation, and hidden movement.":"정보, 타이밍, 적응력과 신중한 움직임으로 가치를 만듭니다.",
"You need growth, movement, and shared direction in relationships.":"관계에서 함께 성장하고 움직이며 방향을 공유하는 것을 중요하게 여깁니다.",
"You attract through warmth, passion, expression, and emotional presence.":"따뜻함, 열정, 표현력과 감정적인 존재감으로 사람을 끌어당깁니다.",
"You love through loyalty, protection, support, and consistency.":"신뢰, 보호, 지지와 한결같음으로 사랑을 표현합니다.",
"You need respect, clarity, boundaries, and trust in relationships.":"관계에서 존중, 명확함, 적절한 경계와 신뢰를 중요하게 여깁니다.",
"You connect deeply, quietly, and selectively through emotional depth.":"감정의 깊이를 통해 조용하고 신중하게 깊은 관계를 맺습니다.",
"Opportunity Hunter":"기회를 찾는 사람","Steady Wealth Builder":"꾸준히 재물을 쌓는 사람","Intuitive Learner":"직관적인 학습자","Structured Learner":"체계적인 학습자","Social Independent":"독립적인 사교형","Competitive Networker":"경쟁 속에서 관계를 만드는 사람","Unconventional Speaker":"틀을 깨는 표현가","Natural Producer":"타고난 창작자","Order Builder":"질서를 세우는 사람","Pressure Fighter":"압박에 맞서는 사람",
"Wealth Instinct":"재물 성향","Learning Style":"학습 방식","Friendship Style":"친구 관계","Expression Style":"표현 방식","Talent Style":"재능 발휘 방식","Social Style":"사회적 성향","Survival Style":"위기 대응 방식",
"You naturally notice money chances, investments, business openings, and practical advantages.":"재물의 기회, 투자, 사업의 가능성과 실질적인 이점을 자연스럽게 포착합니다.",
"You prefer stable income, realistic planning, predictable resources, and long-term accumulation.":"안정적인 수입, 현실적인 계획, 예측 가능한 자원과 장기적인 축적을 선호합니다.",
"You learn through patterns, shortcuts, private study, and unusual insight rather than strict methods.":"엄격한 방식보다는 패턴, 효율적인 접근, 독학과 독특한 통찰로 배웁니다.",
"You learn well through education, tradition, guidance, books, mentors, and organized knowledge.":"교육, 전통, 지도, 책, 멘토와 체계적인 지식을 통해 잘 배웁니다.",
"You enjoy friends and peers, but you also need independence and dislike being controlled.":"친구와 동료를 좋아하지만 독립성도 필요하며 통제받는 것을 싫어합니다.",
"You build relationships through competition, shared goals, survival instinct, and strong peer energy.":"경쟁, 공동의 목표, 생존 본능과 동료 의식을 통해 관계를 맺습니다.",
"You challenge rules, speak sharply, and prefer direct expression over polite conformity.":"규칙에 의문을 던지고 예리하게 말하며, 순응보다 직접적인 표현을 선호합니다.",
"You express talent through skill, output, comfort, creativity, and practical production.":"기술, 결과물, 편안함, 창의성과 실질적인 생산을 통해 재능을 표현합니다.",
"You respect order, reputation, responsibility, and social trust.":"질서, 평판, 책임감과 사회적 신뢰를 존중합니다.",
"You respond strongly under pressure and can grow through discipline, crisis, and challenge.":"압박 속에서 힘을 발휘하며, 절제와 위기, 도전을 통해 성장할 수 있습니다.",
Rat:"쥐",Ox:"소",Tiger:"호랑이",Rabbit:"토끼",Dragon:"용",Snake:"뱀",Horse:"말",Goat:"양",Monkey:"원숭이",Rooster:"닭",Dog:"개",Pig:"돼지",
Blue:"푸른",Red:"붉은",Golden:"황금빛",Silver:"은빛",Black:"검은",Cosmic:"우주의",
"Mixed Family Root":"지지와 부담이 함께하는 가족 배경","Supportive Family Root":"도움을 주는 가족 배경","Limited Ancestral Support":"자립이 중요한 가족 배경",
"Your family background shows both support and pressure. Some help may exist, but self-effort remains important.":"가족 배경에 지지와 압박이 함께 나타납니다. 도움이 있더라도 스스로의 노력이 중요합니다.",
"Your chart shows a favorable family-root signal. It suggests support from family, social order, education, resources, or ancestral background.":"가족, 사회적 질서, 교육, 자원 또는 조상의 배경에서 도움을 얻는 성향으로 해석합니다.",
"Your chart shows a limited family-root signal. It suggests that strong self-effort may be required, with less reliance on family background or ancestral support.":"가족이나 조상의 배경에 의존하기보다 스스로의 노력이 중요하게 나타나는 성향으로 해석합니다.",
"Excellent Potential":"뛰어난 잠재력","Strong Potential":"강한 잠재력","Balanced Potential":"균형 잡힌 잠재력",
"Early Life":"초년","Youth Fortune":"청년기","Middle Life":"중년기","Mature Life":"장년기","Later Life":"노년기",
"Current Cycle":"현재 주기","Next Cycle":"다음 주기","Future Cycle":"미래 주기",
"Stabilize your core direction and build repeatable value.":"중심 방향을 안정시키고 반복해서 만들어낼 수 있는 가치를 쌓아보세요.",
"Convert accumulated skill into money, assets, and opportunity.":"축적한 기술을 수입, 자산과 기회로 연결해 보세요.",
"Use relationships, trust, and reputation as leverage.":"관계, 신뢰와 평판을 성장의 기반으로 활용해 보세요.",
"Foundation period. Family environment, early learning, and emotional imprint are formed.":"가족 환경, 초기 학습과 감정의 바탕이 형성되는 시기입니다.",
"Expansion period. Career direction, relationships, and self-identity begin to take shape.":"직업 방향, 관계와 자아 정체성이 자리를 잡아가는 시기입니다.",
"Achievement period. Wealth, career authority, and major life responsibilities become stronger.":"재물, 직업적 역할과 삶의 주요 책임이 커지는 시기입니다.",
"Influence period. Reputation, leadership, teaching, consulting, or asset consolidation become important.":"평판, 리더십, 교육, 자문과 자산 정리가 중요해지는 시기입니다.",
"Legacy period. Wisdom, family influence, accumulated resources, and spiritual direction become central.":"지혜, 가족에 미치는 영향, 축적한 자원과 내면의 방향이 중심이 되는 시기입니다.",
"Explorer Report":"탐색 리포트","Navigator Report":"방향 리포트","Strategist Report":"전략 리포트","LifeCode Blueprint":"라이프코드 종합 리포트",
"Very Strong":"극신강","Strong":"신강","Balanced":"중화","Weak":"신약","Very Weak":"극신약",
"Spring Earth":"봄의 토","Summer Earth":"여름의 토","Autumn Earth":"가을의 토","Winter Earth":"겨울의 토",
"Expansion, growth, vision, and movement":"확장, 성장, 비전과 움직임","Adaptation, learning, inner growth, and flexibility":"적응, 학습, 내면의 성장과 유연성","Passion, action, visibility, and direct power":"열정, 행동, 존재감과 직접적인 힘","Inner flame, sensitivity, warmth, and hidden intensity":"내면의 불꽃, 감수성, 따뜻함과 숨은 강렬함","Stability, structure, responsibility, and gravity":"안정, 구조, 책임감과 무게감","Nurturing ground, storage, patience, and silent strength":"양육의 바탕, 축적, 인내와 조용한 힘","Judgment, precision, discipline, and refinement":"판단, 정확성, 절제와 정제","Beauty, elegance, internal order, and selective clarity":"아름다움, 우아함, 내적 질서와 명확한 선택","Movement, intelligence, flow, and strategy":"움직임, 지성, 흐름과 전략","Depth, memory, intuition, and hidden knowledge":"깊이, 기억, 직관과 내면의 지식"
}
export function ko(text: string): string {
  if (korean[text]) return korean[text]
  if (text.endsWith(" Field")) return (korean[text.slice(0,-6)] || text.slice(0,-6)) + "의 기운"
  const words = text.split(" ")
  if (words.every(w=>korean[w])) return words.map(w=>korean[w]).join(" ")
  return ""
}
